apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
      name: httpd_app
spec:
  type: NodePort
  selector:
    app: httpd_app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004

